import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import QueryClientProvider from "@/providers/query-client-provider";
import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { SocketStoreProvider } from "@/providers/socket-store-provider";
import "./globals.css";
import { SocketInitializer } from "@/providers/socket-initializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `antialiased bg-background min-h-screen`,
          geistSans.className
        )}
      >
        <SocketStoreProvider>
          <SocketInitializer />
          <QueryClientProvider>{children}</QueryClientProvider>
        </SocketStoreProvider>
        <Toaster richColors expand />
      </body>
    </html>
  );
}
