import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import QueryClientProvider from "@/providers/query-client-provider";
import { SocketInitializer } from "@/providers/socket-initializer";
import { SocketStoreProvider } from "@/providers/socket-store-provider";
import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { ReactScan } from "@/components/react-scan";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          crossOrigin="anonymous"
          src="//unpkg.com/react-scan/dist/auto.global.js"
        />
      </head>
      <body
        className={cn(
          `antialiased bg-background min-h-screen`,
          geistSans.className
        )}
      >
        <QueryClientProvider>
          <SocketStoreProvider>
            <SocketInitializer />
            {children}
          </SocketStoreProvider>
          <Toaster richColors expand />
        </QueryClientProvider>
      </body>
    </html>
  );
}
